import { Chunker, Candidate, TimeSlotOption, AssessmentInfo } from '../types';

export const INITIAL_CHUNKERS: Chunker[] = [];

export const INITIAL_CANDIDATES: Candidate[] = [];

export const TIME_SLOT_OPTIONS: TimeSlotOption[] = [
  {
    id: 'weekday-evening',
    labelVi: 'Tối ngày trong tuần (19:00 - 21:00)',
    labelEn: 'Weekday Evening (19:00 - 21:00)',
    descriptionVi: 'Khung giờ phổ biến nhất cho người đi làm (Thứ 2 - Thứ 6)',
    descriptionEn: 'Most preferred by busy professionals (Mon - Fri)',
    badge: 'Phổ biến / Popular',
  },
  {
    id: 'weekend-morning',
    labelVi: 'Sáng cuối tuần (09:00 - 11:00)',
    labelEn: 'Weekend Morning (09:00 - 11:00)',
    descriptionVi: 'Trí não tỉnh táo nhất cho bài kiểm tra áp lực cao (Thứ 7 - CN)',
    descriptionEn: 'Peak cognitive clarity for high-pressure testing (Sat - Sun)',
    badge: 'Tối ưu MSE / Best MSE',
  },
  {
    id: 'weekend-afternoon',
    labelVi: 'Chiều cuối tuần (14:00 - 16:00)',
    labelEn: 'Weekend Afternoon (14:00 - 16:00)',
    descriptionVi: 'Thời gian thảnh thơi, không vướng bận lịch họp (Thứ 7 - CN)',
    descriptionEn: 'Focused block without weekday meeting interruptions',
  },
  {
    id: 'weekday-afternoon',
    labelVi: 'Chiều ngày trong tuần (14:00 - 16:00)',
    labelEn: 'Weekday Afternoon (14:00 - 16:00)',
    descriptionVi: 'Dành cho lịch làm việc linh hoạt hoặc ca chiều',
    descriptionEn: 'Suited for flexible working hours or afternoon slots',
  },
];

export const GREEN_TEST_INFO: AssessmentInfo = {
  type: 'green',
  titleVi: 'Green Test — Focus Test (%c)',
  titleEn: 'Green Test — Focus Test (%c)',
  subtitleVi: 'Kiểm tra Khả năng Duy trì Tập trung & Phá vỡ Lỗi Quen Mồm',
  subtitleEn: 'Test of Conscious Focus & Elimination of Habitual Slips',
  coefficientVi: '%c (Chỉ số Tập trung Tỉnh thức) & %RFC (Tỉ lệ Quên Yêu Cầu)',
  coefficientEn: '%c (Conscious Concentration) & %RFC (Requests Forgotten Coefficient)',
  duration: '45 phút (1-on-1 với CiC)',
  challengesCount: 49,
  levelsCount: 7,
  coreQuestionVi: 'Liệu bạn có thể bảo toàn một ý niệm và cấu trúc ngữ pháp dưới áp lực phản-thói-quen? Bạn có thể ở lại trọn vẹn với yêu cầu?',
  coreQuestionEn: 'Can you preserve a given idea and its grammatical structure under anti-habitual pressure? Can you stay with the request?',
  focusVi: 'Sự chú ý và năng lực hiện diện. Đo lường cách người học duy trì cộng hưởng MSE (Motion, Sound, Emotion), tuân thủ chỉ dẫn phản-quán-tính và triệt tiêu lỗi phát âm/ngữ pháp thói quen ngay sau đúng 1 lần nhắc nhở.',
  focusEn: 'Attention & Real-time Presence. Measures how learners maintain MSE resonance, obey anti-habitual constraints, and eliminate subconscious speaking errors immediately after 1 single correction.',
  levels: [
    {
      level: 1,
      nameVi: 'Level 1: Calibration (Chuẩn hoá MSE Cơ bản)',
      nameEn: 'Level 1: MSE Resonance Calibration',
      focusVi: 'Kiểm tra nhịp thở, độ mở khẩu hình và phản xạ tiếp nhận chỉ dẫn đầu tiên.',
      focusEn: 'Verifies vocal resonance, jaw release, and initial instruction reception.',
      detailVi: '7 thử thách khởi động với các mẫu câu cốt lõi. CiC quan sát mức độ căng thẳng tiềm thức.',
      detailEn: '7 baseline challenges. CiC observes subconscious vocal tension and readiness.',
    },
    {
      level: 2,
      nameVi: 'Level 2: Structural Lock (Khóa Cấu trúc Ý niệm)',
      nameEn: 'Level 2: Structural Concept Lock',
      focusVi: 'Giữ vững trật tự từ vựng khi bị đảo ngược logic quen thuộc.',
      focusEn: 'Preserving word syntax when familiar conversational patterns are inverted.',
      detailVi: 'Buộc ứng viên nói câu theo cấu trúc chỉ định mà không rơi về phản xạ tiếng mẹ đẻ.',
      detailEn: 'Candidate must speak within specified constraint without slipping into L1 reflex.',
    },
    {
      level: 3,
      nameVi: 'Level 3: Anti-Habitual Inversion (Phản Quán tính)',
      nameEn: 'Level 3: Anti-Habitual Inversion',
      focusVi: 'Cố tình kích hoạt các lỗi quen miệng (ending sounds, thì động từ, mạo từ) rồi kiểm tra phản xạ tự sửa.',
      focusEn: 'Intentionally triggers habitual slips (dropped suffixes, tense drift) to test immediate self-correction.',
      detailVi: 'CiC chỉ nhắc 1 lần. Nếu lặp lại lỗi, %RFC (Requests Forgotten Coefficient) sẽ tăng.',
      detailEn: 'CiC corrects exactly once. Repeat failure escalates the Requests Forgotten Coefficient (%RFC).',
    },
    {
      level: 4,
      nameVi: 'Level 4: Cognitive Friction (Ma sát Nhận thức)',
      nameEn: 'Level 4: Cognitive Friction',
      focusVi: 'Gia tăng tốc độ đưa yêu cầu kết hợp vận động cơ thể (Motion).',
      focusEn: 'Accelerated pacing coupled with physical hand/body motion cues.',
      detailVi: 'Phá vỡ lối dịch thầm trong đầu. Yêu cầu sản sinh câu nói đồng bộ với cử chỉ tay.',
      detailEn: 'Eliminates subvocalization/mental translation; demands synchrony of speech with physical motion.',
    },
    {
      level: 5,
      nameVi: 'Level 5: Emotional Resonance (Cộng hưởng Cảm xúc)',
      nameEn: 'Level 5: Emotional Resonance',
      focusVi: 'Truyền tải ngữ điệu chân thực dưới trạng thái áp lực dồn dập.',
      focusEn: 'Genuine tonal inflection and intonation under rapid-fire questioning.',
      detailVi: 'Đánh giá xem ứng viên có giữ được Sound & Emotion hay bị teo tóp giọng nói khi căng thẳng.',
      detailEn: 'Checks whether Sound & Emotion remain full or shrink into robotic monotonic delivery.',
    },
    {
      level: 6,
      nameVi: 'Level 6: Extended Anti-Drift (Chống Trôi Ý niệm)',
      nameEn: 'Level 6: Extended Anti-Drift',
      focusVi: 'Nói đoạn mạch lạc 90 giây mà không rơi vào các từ đệm vô nghĩa (uh, um, like).',
      focusEn: '90-second structured speech with zero filler words or cognitive wander.',
      detailVi: 'Thử thách độ bền của sự tỉnh thức. Chỉ một thoáng mất tập trung là phạm quy tắc.',
      detailEn: 'Tests cognitive stamina. Any micro-lapse in conscious presence breaks the challenge.',
    },
    {
      level: 7,
      nameVi: 'Level 7: The Master Focus Run (Thử thách Tột đỉnh)',
      nameEn: 'Level 7: The Master Focus Run',
      focusVi: 'Tổng hòa 49 thử thách với 3 quy tắc phản-quán-tính đồng thời.',
      focusEn: 'Integration run of 49 challenges with 3 simultaneous anti-habitual rules.',
      detailVi: 'Đạt điểm %c tối đa chứng minh năng lực kiểm soát hoàn toàn tư duy ngôn ngữ có ý thức.',
      detailEn: 'Achieving high %c confirms complete conscious mastery over spoken language execution.',
    },
  ],
  theoryHighlightsVi: [
    'Không phải bài thi ngữ pháp trắc nghiệm, mà là phiên đối thoại áp lực 1-1 với Chunker-in-Charge (CiC).',
    'Chỉ số %RFC (Requests Forgotten Coefficient) đo lường xem bạn quên yêu cầu bao nhiêu lần sau khi đã được nhắc.',
    'Nguyên lý MSE: Motion (Vận động), Sound (Âm thanh cộng hưởng), Emotion (Cảm xúc sống động) thay thế học vẹt.',
  ],
  theoryHighlightsEn: [
    'Not an automated quiz, but a live 1-on-1 conscious performance assessment with a Chunker-in-Charge (CiC).',
    '%RFC (Requests Forgotten Coefficient) objectively measures how often you repeat a habit after 1 correction.',
    'MSE Framework: Motion, resonant Sound, and authentic Emotion supersede rote mechanical memorization.',
  ],
};

export const RED_TEST_INFO: AssessmentInfo = {
  type: 'red',
  titleVi: 'Red Test — Improvisation Test (%r)',
  titleEn: 'Red Test — Improvisation Test (%r)',
  subtitleVi: 'Kiểm tra Khả năng Bẻ lái Tư duy & Ứng biến Logic Thời gian thực',
  subtitleEn: 'Test of Instant Idea Redirection & Sequential Logic Agility',
  coefficientVi: '%r (Chỉ số Ứng biến Linh hoạt) & %CR (Độ Mạch lạc Logic)',
  coefficientEn: '%r (Cognitive Improvisation) & %CR (Coherence Ratio)',
  duration: '45 phút (1-on-1 với CiC)',
  challengesCount: 49,
  levelsCount: 7,
  coreQuestionVi: 'Bạn có thể lập tức chuyển hướng dòng suy nghĩ khi nhận gợi ý ngôn ngữ bất ngờ mà câu chuyện vẫn hoàn toàn hợp lý?',
  coreQuestionEn: 'Can you instantly redirect your idea under random logic hints while remaining coherent?',
  focusVi: 'Ý đồ và sự nhanh nhạy của não bộ. Đo lường cách ứng viên điều hướng một ý niệm đang diễn ra trước các từ khóa/gợi ý ngẫu nhiên, bất chấp kịch bản chuẩn bị trước. Ngữ pháp chỉ là thứ yếu; logic và sự hiện diện mới là quyết định.',
  focusEn: 'Intention & Cognitive Agility. Assesses how learners redirect an unfolding idea in real-time under sudden, random linguistic hints while preserving sequential logic. Rote answers are impossible; grammar is secondary to coherence and presence.',
  levels: [
    {
      level: 1,
      nameVi: 'Level 1: Semantic Pivot (Bẻ lái Từ vựng)',
      nameEn: 'Level 1: Semantic Pivot',
      focusVi: 'Đang nói về chủ đề A, nhận 1 từ khóa không liên quan và phải lồng ghép tự nhiên trong 3 giây.',
      focusEn: 'Mid-sentence topic A redirection: integrate an unrelated keyword within 3 seconds naturally.',
      detailVi: 'Kiểm tra phản xạ đóng băng (freeze response) hoặc né tránh từ khóa của ứng viên.',
      detailEn: 'Detects mental freeze response or avoidance tricks under unexpected input.',
    },
    {
      level: 2,
      nameVi: 'Level 2: Dual Prompt Juggling (Tung hứng 2 Dòng Ý niệm)',
      nameEn: 'Level 2: Dual Prompt Juggling',
      focusVi: 'Duy trì hai luồng đối lập và đan xen chúng thành một kết luận hợp lý.',
      focusEn: 'Holding two contradictory premises and weaving them into a logical outcome.',
      detailVi: 'Buộc não bộ thoát khỏi các câu nói mẫu thuộc lòng kiểu IELTS hay TOEIC.',
      detailEn: 'Forces the brain out of pre-memorized speech scripts and formulaic templates.',
    },
    {
      level: 3,
      nameVi: 'Level 3: Sudden Reality Shift (Chuyển dịch Bối cảnh)',
      nameEn: 'Level 3: Sudden Reality Shift',
      focusVi: 'Thay đổi hoàn toàn bối cảnh giao tiếp (từ phỏng vấn trang trọng sang tình huống khẩn cấp).',
      focusEn: 'Abrupt shift in communicative context (from corporate meeting to urgent crisis).',
      detailVi: 'Đánh giá khả năng điều chỉnh giọng điệu và thái độ ngay lập tức.',
      detailEn: 'Measures immediate register, tonality, and emotional posture adaptation.',
    },
    {
      level: 4,
      nameVi: 'Level 4: Narrative Trap Escape (Thoát bẫy Tường thuật)',
      nameEn: 'Level 4: Narrative Trap Escape',
      focusVi: 'CiC đưa ra các giả định sai logic để ứng viên bảo vệ hoặc bẻ lái lập luận.',
      focusEn: 'CiC injects logical paradoxes; candidate must maneuver without stalling.',
      detailVi: 'Không được phép nói "I don\'t know" hay im lặng quá 2 giây.',
      detailEn: 'Zero tolerance for "I don\'t know" cop-outs or dead air exceeding 2 seconds.',
    },
    {
      level: 5,
      nameVi: 'Level 5: Micro-Metaphor Generation (Kiến tạo Ẩn dụ Tức thời)',
      nameEn: 'Level 5: Instant Metaphor Generation',
      focusVi: 'Giải thích một khái niệm trừu tượng bằng hình ảnh trực quan nhận ngẫu nhiên.',
      focusEn: 'Explaining abstract principles using spontaneously assigned visual metaphors.',
      detailVi: 'Đòi hỏi sự liên kết sâu sắc giữa bán cầu não sáng tạo và trung tâm ngôn ngữ.',
      detailEn: 'Demands deep cross-hemispheric synergy between creative imagination and verbal flow.',
    },
    {
      level: 6,
      nameVi: 'Level 6: High-Velocity Story Chain (Chuỗi Câu chuyện Thần tốc)',
      nameEn: 'Level 6: High-Velocity Story Chain',
      focusVi: '7 từ khóa ngẫu nhiên xuất hiện nối tiếp nhau mỗi 10 giây trong khi vẫn duy trì một câu chuyện duy nhất.',
      focusEn: '7 sequential random tokens introduced every 10s while maintaining a single story arc.',
      detailVi: 'Độ khó tối đa về tính mạch lạc (Coherence Ratio) và sự bình tĩnh dưới áp lực.',
      detailEn: 'Extreme test of sequential coherence and neurological calm under real-time chaos.',
    },
    {
      level: 7,
      nameVi: 'Level 7: The Master Improv Finale (Đỉnh cao Ứng biến)',
      nameEn: 'Level 7: The Master Improv Finale',
      focusVi: 'Trình bày giải pháp bất ngờ trước bài toán hóc búa do CiC liên tục thay đổi biến số.',
      focusEn: 'Complex problem-solving presentation where CiC dynamically alters variables live.',
      detailVi: 'Chỉ số %r cao khẳng định năng lực ứng biến tự nhiên và sự tự tin không thể lay chuyển.',
      detailEn: 'Peak %r score proves authentic spontaneous fluency and unshakeable communicative presence.',
    },
  ],
  theoryHighlightsVi: [
    'Triệt tiêu hoàn toàn thói quen học tủ, học vẹt, nói theo kịch bản chuẩn bị sẵn.',
    'Chỉ số %r (Improvisation) đo đạc tốc độ kết nối nơ-ron và độ linh hoạt khi đối mặt tình huống bất định.',
    'Nguyên lý Ý đồ trước Ngữ pháp: Một câu đúng ngữ pháp nhưng vô hồn và ngắt quãng sẽ xếp sau một phản xạ sống động và mạch lạc.',
  ],
  theoryHighlightsEn: [
    'Completely eradicates reliance on rote memory, pre-written scripts, or robotic speech formulas.',
    '%r score measures neuro-linguistic agility and composure in unpredictable conversations.',
    'Intention Precedes Grammar: A technically accurate yet disjointed response ranks below vivid, coherent presence.',
  ],
};
