import React, { useState, useMemo } from 'react';
import { BarChart3, TrendingUp, Award, Users, ArrowUpDown } from 'lucide-react';
import { Chunker } from '../types';

interface Props {
  chunkers: Chunker[];
  lang: 'vi' | 'en';
}

export const ChunkerReferralAnalyticsCard: React.FC<Props> = ({ chunkers, lang }) => {
  const [sortBy, setSortBy] = useState<'count' | 'name'>('count');
  const [filterActiveOnly, setFilterActiveOnly] = useState(false);

  // Transactional aggregates include all pages of candidates.
  const analyticsData = useMemo(() => {
    const directCount = chunkers.find((ch) => ch.code === 'PILOT100')?.referralCount || 0;
    const list = chunkers.filter((ch) => ch.code !== 'PILOT100').map((ch) => {
      const count = ch.referralCount || 0;
      return {
        id: ch.id || ch.code,
        name: ch.name,
        code: ch.code,
        email: ch.email,
        count,
        active: ch.active,
      };
    });

    const totalChunkerReferrals = list.reduce((sum, item) => sum + item.count, 0);
    return {
      list,
      totalChunkerReferrals,
      directCount,
      totalAll: totalChunkerReferrals + directCount,
    };
  }, [chunkers]);

  // Sorted and filtered list
  const processedList = useMemo(() => {
    let result = [...analyticsData.list];

    if (filterActiveOnly) {
      result = result.filter((item) => item.count > 0);
    }

    if (sortBy === 'count') {
      result.sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
    } else {
      result.sort((a, b) => a.name.localeCompare(b.name));
    }

    return result;
  }, [analyticsData.list, sortBy, filterActiveOnly]);

  const maxCount = useMemo(() => {
    const counts = processedList.map((i) => i.count);
    return Math.max(...counts, 1);
  }, [processedList]);

  const topPerformer = useMemo(() => {
    if (analyticsData.list.length === 0) return null;
    const sorted = [...analyticsData.list].sort((a, b) => b.count - a.count);
    return sorted[0]?.count > 0 ? sorted[0] : null;
  }, [analyticsData.list]);

  const activeChunkersWithReferrals = useMemo(() => {
    return analyticsData.list.filter((c) => c.count > 0).length;
  }, [analyticsData.list]);

  const avgReferrals = useMemo(() => {
    if (chunkers.length === 0) return 0;
    return (analyticsData.totalChunkerReferrals / chunkers.length).toFixed(1);
  }, [analyticsData.totalChunkerReferrals, chunkers.length]);

  return (
    <div className="border border-[rgba(10,10,10,0.14)] p-6 bg-white space-y-6">
      {/* Header & Controls */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-[rgba(10,10,10,0.12)] pb-4">
        <div>
          <div className="flex items-center gap-2">
            <BarChart3 className="w-4 h-4 text-[#c81e16]" />
            <span className="text-[10.5px] uppercase tracking-[0.2em] font-semibold text-[#0a0a0a]/50">
              {lang === 'vi' ? 'PHÂN TÍCH HIỆU SUẤT GIỚI THIỆU' : 'REFERRAL PERFORMANCE ANALYTICS'}
            </span>
          </div>
          <h3 className="text-[19px] font-bold text-[#0a0a0a] mt-0.5">
            {lang === 'vi' ? 'Biểu Đồ Số Lượng Đăng Ký Theo Từng Chunker' : 'Referral Distribution by Chunker'}
          </h3>
          <p className="text-[12.5px] text-[#0a0a0a]/65 font-light mt-0.5">
            {lang === 'vi'
              ? 'Theo dõi trực quan tỷ lệ chuyển đổi và số lượng ứng viên được giới thiệu bởi từng thành viên Chunker trong chiến dịch.'
              : 'Visual comparison of candidate referrals generated by each chunker referral code.'}
          </p>
        </div>

        {/* Filters & Sorting */}
        <div className="flex flex-wrap items-center gap-2">
          <button
            type="button"
            onClick={() => setFilterActiveOnly(!filterActiveOnly)}
            className={`px-3 py-1.5 text-xs font-mono border transition-colors cursor-pointer ${
              filterActiveOnly
                ? 'border-[#0a0a0a] bg-[#0a0a0a] text-white font-semibold'
                : 'border-[rgba(10,10,10,0.18)] bg-white text-[#0a0a0a]/70 hover:border-[#0a0a0a]'
            }`}
          >
            {filterActiveOnly
              ? (lang === 'vi' ? 'Đang lọc: Có giới thiệu (>0)' : 'Filter: Referrals > 0')
              : (lang === 'vi' ? 'Tất cả Chunkers' : 'All Chunkers')}
          </button>

          <button
            type="button"
            onClick={() => setSortBy(sortBy === 'count' ? 'name' : 'count')}
            className="px-3 py-1.5 text-xs font-mono border border-[rgba(10,10,10,0.18)] bg-white hover:border-[#0a0a0a] text-[#0a0a0a] flex items-center gap-1.5 transition-colors cursor-pointer"
          >
            <ArrowUpDown className="w-3 h-3 text-[#c81e16]" />
            <span>
              {sortBy === 'count'
                ? (lang === 'vi' ? 'Xếp theo: Số lượt cao nhất' : 'Sort: Highest Referrals')
                : (lang === 'vi' ? 'Xếp theo: Tên (A - Z)' : 'Sort: Name (A-Z)')}
            </span>
          </button>
        </div>
      </div>

      {/* KPI Highlights Bar */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <div className="p-3.5 bg-slate-50 border border-[rgba(10,10,10,0.08)]">
          <div className="text-[10px] uppercase font-mono tracking-wider text-[#0a0a0a]/50">
            {lang === 'vi' ? 'TỔNG QUA CHUNKER' : 'TOTAL CHUNKER REFS'}
          </div>
          <div className="text-[26px] font-bold font-mono text-[#0a0a0a] leading-none mt-1.5">
            {analyticsData.totalChunkerReferrals}
          </div>
          <div className="text-[11px] text-[#0a0a0a]/50 font-light mt-1">
            {lang === 'vi' ? 'Ứng viên được giới thiệu' : 'Referred candidates'}
          </div>
        </div>

        <div className="p-3.5 bg-slate-50 border border-[rgba(10,10,10,0.08)]">
          <div className="text-[10px] uppercase font-mono tracking-wider text-[#0a0a0a]/50 flex items-center gap-1">
            <Award className="w-3 h-3 text-[#c81e16]" />
            <span>{lang === 'vi' ? 'DẪN ĐẦU CHIẾN DỊCH' : 'TOP PERFORMER'}</span>
          </div>
          <div className="text-[18px] font-bold font-mono text-[#c81e16] truncate leading-tight mt-1.5">
            {topPerformer ? topPerformer.name : '—'}
          </div>
          <div className="text-[11px] text-[#0a0a0a]/50 font-mono mt-1">
            {topPerformer ? `${topPerformer.count} lượt (${topPerformer.code})` : (lang === 'vi' ? 'Chưa có dữ liệu' : 'No records yet')}
          </div>
        </div>

        <div className="p-3.5 bg-slate-50 border border-[rgba(10,10,10,0.08)]">
          <div className="text-[10px] uppercase font-mono tracking-wider text-[#0a0a0a]/50">
            {lang === 'vi' ? 'CHUNKERS CÓ CHUYỂN ĐỔI' : 'ACTIVE REFERRERS'}
          </div>
          <div className="text-[26px] font-bold font-mono text-[#0a0a0a] leading-none mt-1.5">
            {activeChunkersWithReferrals} / {chunkers.length}
          </div>
          <div className="text-[11px] text-[#0a0a0a]/50 font-light mt-1">
            {chunkers.length > 0
              ? `${Math.round((activeChunkersWithReferrals / chunkers.length) * 100)}% thành viên có lượt`
              : '0%'}
          </div>
        </div>

        <div className="p-3.5 bg-slate-50 border border-[rgba(10,10,10,0.08)]">
          <div className="text-[10px] uppercase font-mono tracking-wider text-[#0a0a0a]/50">
            {lang === 'vi' ? 'TRUNG BÌNH / CHUNKER' : 'AVG REFS / CHUNKER'}
          </div>
          <div className="text-[26px] font-bold font-mono text-[#0a0a0a] leading-none mt-1.5">
            {avgReferrals}
          </div>
          <div className="text-[11px] text-[#0a0a0a]/50 font-light mt-1">
            {analyticsData.directCount > 0
              ? `+${analyticsData.directCount} direct applications`
              : (lang === 'vi' ? 'Tỷ suất phân bổ' : 'Average density')}
          </div>
        </div>
      </div>

      {/* Bar Chart Visualization */}
      <div className="space-y-3 pt-2">
        <div className="flex items-center justify-between text-[11px] font-mono uppercase tracking-wider text-[#0a0a0a]/50 pb-1 border-b border-[rgba(10,10,10,0.08)]">
          <span>Chunker Member &amp; Code</span>
          <span>Referral Count &amp; Share</span>
        </div>

        {processedList.length === 0 ? (
          <div className="py-10 text-center text-[#0a0a0a]/50 text-xs font-mono">
            {lang === 'vi' ? 'Chưa có thành viên Chunker nào phù hợp bộ lọc.' : 'No chunker records match filter.'}
          </div>
        ) : (
          <div className="space-y-2.5">
            {processedList.map((item, index) => {
              const percentage = Math.round((item.count / maxCount) * 100);
              const shareOfTotal =
                analyticsData.totalChunkerReferrals > 0
                  ? Math.round((item.count / analyticsData.totalChunkerReferrals) * 100)
                  : 0;

              const isTop = index === 0 && item.count > 0;

              return (
                <div
                  key={item.id}
                  className="group p-2.5 hover:bg-slate-50 transition-colors border border-transparent hover:border-[rgba(10,10,10,0.08)] rounded-xs"
                >
                  {/* Top line: Label, Code, Count */}
                  <div className="flex items-center justify-between text-xs mb-1.5">
                    <div className="flex items-center gap-2 min-w-0">
                      <span className="font-mono text-[11px] text-[#0a0a0a]/40 w-5 shrink-0">
                        #{index + 1}
                      </span>
                      <span className="font-semibold text-[#0a0a0a] truncate max-w-[200px] sm:max-w-xs">
                        {item.name}
                      </span>
                      <span className="font-mono text-[10.5px] px-1.5 py-0.2 bg-slate-100 border border-slate-200 text-[#0a0a0a]/75 shrink-0">
                        {item.code}
                      </span>
                      {isTop && (
                        <span className="text-[10px] font-mono px-1.5 py-0.2 bg-rose-50 text-[#c81e16] border border-rose-200 font-semibold shrink-0">
                          TOP 1
                        </span>
                      )}
                    </div>

                    <div className="flex items-center gap-3 shrink-0 font-mono">
                      <span className="text-[13px] font-bold text-[#0a0a0a]">
                        {item.count} <span className="text-[10.5px] font-normal text-[#0a0a0a]/50">{lang === 'vi' ? 'lượt' : 'refs'}</span>
                      </span>
                      <span className="text-[11px] text-[#0a0a0a]/50 w-10 text-right">
                        {shareOfTotal}%
                      </span>
                    </div>
                  </div>

                  {/* Bar track and proportional fill bar */}
                  <div className="w-full h-3 bg-slate-100 overflow-hidden rounded-xs relative">
                    <div
                      className={`h-full transition-all duration-500 ${
                        isTop
                          ? 'bg-[#c81e16]'
                          : item.count > 0
                          ? 'bg-[#0a0a0a]'
                          : 'bg-slate-300'
                      }`}
                      style={{ width: `${Math.max(percentage, item.count > 0 ? 4 : 0)}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Direct vs Chunker Breakdown Footer */}
      <div className="pt-3 border-t border-[rgba(10,10,10,0.08)] flex flex-col sm:flex-row sm:items-center justify-between text-xs text-[#0a0a0a]/60 gap-2">
        <div className="flex items-center gap-4 font-mono">
          <div className="flex items-center gap-1.5">
            <span className="w-2.5 h-2.5 bg-[#c81e16] inline-block" />
            <span>Chunker Referrals: <strong>{analyticsData.totalChunkerReferrals}</strong></span>
          </div>
          <div className="flex items-center gap-1.5">
            <span className="w-2.5 h-2.5 bg-slate-400 inline-block" />
            <span>Direct Pilot: <strong>{analyticsData.directCount}</strong></span>
          </div>
        </div>
        <div className="text-[11px] text-[#0a0a0a]/50 font-mono">
          Total Assessment Pool: {analyticsData.totalAll}
        </div>
      </div>
    </div>
  );
};
